/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Note = IDL.Record({ 'name' : IDL.Text, 'octave' : IDL.Nat });
export const Song = IDL.Record({
  'bars' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'annotations' : IDL.Text,
  'notes' : IDL.Vec(IDL.Tuple(Note, IDL.Nat)),
});
export const HoleLayout = IDL.Record({
  'size' : IDL.Float64,
  'position' : IDL.Record({ 'x' : IDL.Float64, 'y' : IDL.Float64 }),
});
export const SoundSettings = IDL.Record({
  'reverb' : IDL.Record({
    'mix' : IDL.Float64,
    'amount' : IDL.Float64,
    'delay' : IDL.Float64,
    'reverbType' : IDL.Text,
  }),
  'tone' : IDL.Record({ 'character' : IDL.Float64, 'warmth' : IDL.Float64 }),
  'pitchOffset' : IDL.Record({
    'frequencyRatio' : IDL.Float64,
    'semitones' : IDL.Int,
    'cents' : IDL.Int,
  }),
});
export const SoundPreset = IDL.Record({
  'soundSettings' : SoundSettings,
  'name' : IDL.Text,
  'ocarinaImage' : IDL.Opt(IDL.Text),
});
export const OcarinaLayout = IDL.Record({
  'holes' : IDL.Vec(HoleLayout),
  'imageRef' : IDL.Text,
  'mouthpiece' : IDL.Record({
    'thickness' : IDL.Float64,
    'length' : IDL.Float64,
    'position' : IDL.Record({ 'x' : IDL.Float64, 'y' : IDL.Float64 }),
    'orientation' : IDL.Float64,
  }),
});
export const FingeringPattern = IDL.Vec(IDL.Bool);

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addSong' : IDL.Func([Song], [], []),
  'getAllHoleLayouts' : IDL.Func([], [IDL.Vec(HoleLayout)], ['query']),
  'getAllPresetSongs' : IDL.Func([], [IDL.Vec(Song)], ['query']),
  'getAllSongs' : IDL.Func([], [IDL.Vec(Song)], ['query']),
  'getAllSoundPresets' : IDL.Func([], [IDL.Vec(SoundPreset)], ['query']),
  'getAllUsers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Text))],
      ['query'],
    ),
  'getCurrentOctave' : IDL.Func([], [IDL.Nat], ['query']),
  'getCustomOcarinaLayout' : IDL.Func([], [IDL.Opt(OcarinaLayout)], ['query']),
  'getFingeringPattern' : IDL.Func([Note], [FingeringPattern], ['query']),
  'getHoleLayout' : IDL.Func([IDL.Nat], [HoleLayout], ['query']),
  'getNumberOfHoles' : IDL.Func([], [IDL.Nat], ['query']),
  'getSoundPreset' : IDL.Func([IDL.Text], [SoundPreset], ['query']),
  'getSoundSettings' : IDL.Func([], [SoundSettings], ['query']),
  'getUsername' : IDL.Func([IDL.Principal], [IDL.Text], ['query']),
  'registerUser' : IDL.Func([IDL.Text], [], []),
  'saveSoundPreset' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [], []),
  'setCurrentOctave' : IDL.Func([IDL.Nat], [], []),
  'updateCustomOcarinaLayout' : IDL.Func([OcarinaLayout], [], []),
  'updateFingeringPattern' : IDL.Func([Note, FingeringPattern], [], []),
  'updateSoundSettings' : IDL.Func([SoundSettings], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Note = IDL.Record({ 'name' : IDL.Text, 'octave' : IDL.Nat });
  const Song = IDL.Record({
    'bars' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'annotations' : IDL.Text,
    'notes' : IDL.Vec(IDL.Tuple(Note, IDL.Nat)),
  });
  const HoleLayout = IDL.Record({
    'size' : IDL.Float64,
    'position' : IDL.Record({ 'x' : IDL.Float64, 'y' : IDL.Float64 }),
  });
  const SoundSettings = IDL.Record({
    'reverb' : IDL.Record({
      'mix' : IDL.Float64,
      'amount' : IDL.Float64,
      'delay' : IDL.Float64,
      'reverbType' : IDL.Text,
    }),
    'tone' : IDL.Record({ 'character' : IDL.Float64, 'warmth' : IDL.Float64 }),
    'pitchOffset' : IDL.Record({
      'frequencyRatio' : IDL.Float64,
      'semitones' : IDL.Int,
      'cents' : IDL.Int,
    }),
  });
  const SoundPreset = IDL.Record({
    'soundSettings' : SoundSettings,
    'name' : IDL.Text,
    'ocarinaImage' : IDL.Opt(IDL.Text),
  });
  const OcarinaLayout = IDL.Record({
    'holes' : IDL.Vec(HoleLayout),
    'imageRef' : IDL.Text,
    'mouthpiece' : IDL.Record({
      'thickness' : IDL.Float64,
      'length' : IDL.Float64,
      'position' : IDL.Record({ 'x' : IDL.Float64, 'y' : IDL.Float64 }),
      'orientation' : IDL.Float64,
    }),
  });
  const FingeringPattern = IDL.Vec(IDL.Bool);
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addSong' : IDL.Func([Song], [], []),
    'getAllHoleLayouts' : IDL.Func([], [IDL.Vec(HoleLayout)], ['query']),
    'getAllPresetSongs' : IDL.Func([], [IDL.Vec(Song)], ['query']),
    'getAllSongs' : IDL.Func([], [IDL.Vec(Song)], ['query']),
    'getAllSoundPresets' : IDL.Func([], [IDL.Vec(SoundPreset)], ['query']),
    'getAllUsers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Text))],
        ['query'],
      ),
    'getCurrentOctave' : IDL.Func([], [IDL.Nat], ['query']),
    'getCustomOcarinaLayout' : IDL.Func(
        [],
        [IDL.Opt(OcarinaLayout)],
        ['query'],
      ),
    'getFingeringPattern' : IDL.Func([Note], [FingeringPattern], ['query']),
    'getHoleLayout' : IDL.Func([IDL.Nat], [HoleLayout], ['query']),
    'getNumberOfHoles' : IDL.Func([], [IDL.Nat], ['query']),
    'getSoundPreset' : IDL.Func([IDL.Text], [SoundPreset], ['query']),
    'getSoundSettings' : IDL.Func([], [SoundSettings], ['query']),
    'getUsername' : IDL.Func([IDL.Principal], [IDL.Text], ['query']),
    'registerUser' : IDL.Func([IDL.Text], [], []),
    'saveSoundPreset' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [], []),
    'setCurrentOctave' : IDL.Func([IDL.Nat], [], []),
    'updateCustomOcarinaLayout' : IDL.Func([OcarinaLayout], [], []),
    'updateFingeringPattern' : IDL.Func([Note, FingeringPattern], [], []),
    'updateSoundSettings' : IDL.Func([SoundSettings], [], []),
  });
};

export const init = ({ IDL }) => { return []; };