/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type FingeringPattern = Array<boolean>;
export interface HoleLayout {
  'size' : number,
  'position' : { 'x' : number, 'y' : number },
}
export interface Note { 'name' : string, 'octave' : bigint }
export interface OcarinaLayout {
  'holes' : Array<HoleLayout>,
  'imageRef' : string,
  'mouthpiece' : {
    'thickness' : number,
    'length' : number,
    'position' : { 'x' : number, 'y' : number },
    'orientation' : number,
  },
}
export interface Song {
  'bars' : bigint,
  'name' : string,
  'description' : string,
  'annotations' : string,
  'notes' : Array<[Note, bigint]>,
}
export interface SoundPreset {
  'soundSettings' : SoundSettings,
  'name' : string,
  'ocarinaImage' : [] | [string],
}
export interface SoundSettings {
  'reverb' : {
    'mix' : number,
    'amount' : number,
    'delay' : number,
    'reverbType' : string,
  },
  'tone' : { 'character' : number, 'warmth' : number },
  'pitchOffset' : {
    'frequencyRatio' : number,
    'semitones' : bigint,
    'cents' : bigint,
  },
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addSong' : ActorMethod<[Song], undefined>,
  'getAllHoleLayouts' : ActorMethod<[], Array<HoleLayout>>,
  'getAllPresetSongs' : ActorMethod<[], Array<Song>>,
  'getAllSongs' : ActorMethod<[], Array<Song>>,
  'getAllSoundPresets' : ActorMethod<[], Array<SoundPreset>>,
  'getAllUsers' : ActorMethod<[], Array<[Principal, string]>>,
  'getCurrentOctave' : ActorMethod<[], bigint>,
  'getCustomOcarinaLayout' : ActorMethod<[], [] | [OcarinaLayout]>,
  'getFingeringPattern' : ActorMethod<[Note], FingeringPattern>,
  'getHoleLayout' : ActorMethod<[bigint], HoleLayout>,
  'getNumberOfHoles' : ActorMethod<[], bigint>,
  'getSoundPreset' : ActorMethod<[string], SoundPreset>,
  'getSoundSettings' : ActorMethod<[], SoundSettings>,
  'getUsername' : ActorMethod<[Principal], string>,
  'registerUser' : ActorMethod<[string], undefined>,
  'saveSoundPreset' : ActorMethod<[string, [] | [string]], undefined>,
  'setCurrentOctave' : ActorMethod<[bigint], undefined>,
  'updateCustomOcarinaLayout' : ActorMethod<[OcarinaLayout], undefined>,
  'updateFingeringPattern' : ActorMethod<[Note, FingeringPattern], undefined>,
  'updateSoundSettings' : ActorMethod<[SoundSettings], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];